---
# wifimon vagrant setup

- hosts: wifimon
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - ansible-role-kibana
    - ansible-elasticsearch
    - ansible-role-wifimon
  vars:
    host_name: "localhost"
    node_name: "wifimon"
    sha_key: "brendan"
    wifimon_user: "wifimon_user"
    wifimon_pass: "wifimonpass"
    es_config:
      node.name: "{{ node_name }}"
      cluster.name: "elasticsearch"
      network.host: "{{ host_name }}"
      discovery.seed_hosts: "{{ host_name }}"
      cluster.initial_master_nodes: "{{ node_name }}"
      xpack.ml.enabled: false
      xpack.security.enabled: false
      node.master: true
      node.voting_only: false
      node.data: true
      node.ingest: true
      node.ml: false
      cluster.remote.connect: false

